-- Fluent — migration 006: allow the app to grow the text bank at runtime.
-- Passages generated by the Gemini-backed dynamic passage endpoint
-- (app/api/generate-passage) are inserted into text_bank using the
-- requesting user's own session, so every signed-in user needs insert
-- rights here. This is shared practice content, not sensitive data.

create policy "text_bank: insert (any signed-in user)" on public.text_bank
  for insert with check (auth.role() = 'authenticated');
